// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContainerImageResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerImageResponseBody{}

// ContainerImageResponseBody struct for ContainerImageResponseBody
type ContainerImageResponseBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Items []ContainerImage `json:"items"`
}

type _ContainerImageResponseBody ContainerImageResponseBody

// NewContainerImageResponseBody instantiates a new ContainerImageResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerImageResponseBody(items []ContainerImage) *ContainerImageResponseBody {
	this := ContainerImageResponseBody{}
	this.Items = items
	return &this
}

// NewContainerImageResponseBodyWithDefaults instantiates a new ContainerImageResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerImageResponseBodyWithDefaults() *ContainerImageResponseBody {
	this := ContainerImageResponseBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *ContainerImageResponseBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerImageResponseBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *ContainerImageResponseBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *ContainerImageResponseBody) SetSchema(v string) {
	o.Schema = &v
}

// GetItems returns the Items field value
// If the value is explicit nil, the zero value for []ContainerImage will be returned
func (o *ContainerImageResponseBody) GetItems() []ContainerImage {
	if o == nil {
		var ret []ContainerImage
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerImageResponseBody) GetItemsOk() ([]ContainerImage, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ContainerImageResponseBody) SetItems(v []ContainerImage) {
	o.Items = v
}

func (o ContainerImageResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerImageResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

func (o *ContainerImageResponseBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerImageResponseBody := _ContainerImageResponseBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainerImageResponseBody)

	if err != nil {
		return err
	}

	*o = ContainerImageResponseBody(varContainerImageResponseBody)

	return err
}

type NullableContainerImageResponseBody struct {
	value *ContainerImageResponseBody
	isSet bool
}

func (v NullableContainerImageResponseBody) Get() *ContainerImageResponseBody {
	return v.value
}

func (v *NullableContainerImageResponseBody) Set(val *ContainerImageResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerImageResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerImageResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerImageResponseBody(val *ContainerImageResponseBody) *NullableContainerImageResponseBody {
	return &NullableContainerImageResponseBody{value: val, isSet: true}
}

func (v NullableContainerImageResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerImageResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


