---
before:
  hooks:
    - "go mod tidy"

builds:
  - id: "cli"
    env:
      - "CGO_ENABLED=0"
    goos:
      - "linux"
      - "darwin"
    main: "./internal/pkg/cmd"
    binary: "bin/service"
    ldflags:
      - "-s -w -X github.com/klearwave/service-info/internal/pkg/api.AuthPassword={{ .Env.GITHUB_TOKEN }} -extldflags '-static'"

archives:
  - name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - "README.md"
      - "LICENSE"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Version }}-snapshot-{{ .ShortCommit }}"

changelog:
  sort: "asc"
  use: "github"
  filters:
    exclude:
      - '^docs(\(.*\))?:'
      - '^test(\(.*\))?:'
      - '^ci(\(.*\))?:'
      - '^chore(\(.*\))?:'
      - '^build(\(.*\))?:'

release:
  replace_existing_artifacts: true
  make_latest: true
  include_meta: true
