---
name: Generate Client Code
on:
  push:
    branches:
      - main

jobs:
  generate-client-code:
    name: Generate Client Code
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Generate Client Code
        run: make client

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add client/* || true
          git commit -m "chore: auto-update client code [skip ci]" || echo "No changes to commit"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:${{ github.ref }}
    