---
name: Release
on:
  push:
    tags:
      - "*"
env:
  IMAGE: "${{ vars.ORG_IMAGE_REGISTRY }}/${{ github.repository_owner }}/${{ github.event.repository.name }}"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      actions: "read"
      security-events: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ORG_IMAGE_REGISTRY }}
          username: ${{ secrets.ORG_IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.ORG_IMAGE_REGISTRY_PASSWORD }}

      - name: Build and Load
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: "${{ env.IMAGE }}:${{ github.ref_name }},${{ env.IMAGE }}:latest"

      - name: Scan for Vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: "${{ env.IMAGE }}:latest"
          severity_threshold: HIGH
          annotations: true

      - name: Upload SARIF file
        if: ${{ steps.scan.outputs.sarif != '' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: "."
          platforms: "linux/amd64,linux/arm64"
          push: true
          tags: "${{ env.IMAGE }}:${{ github.ref_name }},${{ env.IMAGE }}:latest"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean -f  ./.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_ACCESS_TOKEN }}
